require 'rspec'
require './laba3/Task3.rb'

RSpec.describe "Main" do
  it "task3" do
    allow_any_instance_of(Kernel).to receive(:gets).and_return("j\n","b\n","d\n",50,"d\n",10000,"d\n",5550,"d\n",500,"w\n",50,"w\n",10000,"w\n",5550,"w\n",7000,"w\n",1500,"q\n")
    expect{task3}.to output("Deposit money (Press D)\nWithdraw money (Press W)\nCheck balance (Press B)\nQuit (Press Q)\nNo such command exists, please enter the correct letter\nDeposit money (Press D)\nWithdraw money (Press W)\nCheck balance (Press B)\nQuit (Press Q)\nYour balance: 5000\nDeposit money (Press D)\nWithdraw money (Press W)\nCheck balance (Press B)\nQuit (Press Q)\nATM accepts the following bills:\n100\n500\n1000\n2000\n5000\nYou can deposit no more than 9900 at a time\nEnter your amount:\nYou entered the amount less than the minimum, please try again\nDeposit money (Press D)\nWithdraw money (Press W)\nCheck balance (Press B)\nQuit (Press Q)\nATM accepts the following bills:\n100\n500\n1000\n2000\n5000\nYou can deposit no more than 9900 at a time\nEnter your amount:\nYou entered the amount that exceeds the maximum deposit at a time, please try again\nDeposit money (Press D)\nWithdraw money (Press W)\nCheck balance (Press B)\nQuit (Press Q)\nATM accepts the following bills:\n100\n500\n1000\n2000\n5000\nYou can deposit no more than 9900 at a time\nEnter your amount:\nYou entered the wrong bill, please try again\nDeposit money (Press D)\nWithdraw money (Press W)\nCheck balance (Press B)\nQuit (Press Q)\nATM accepts the following bills:\n100\n500\n1000\n2000\n5000\nYou can deposit no more than 9900 at a time\nEnter your amount:\nYour balance: 5500\nDeposit money (Press D)\nWithdraw money (Press W)\nCheck balance (Press B)\nQuit (Press Q)\nATM dispenses the following bills:\n100\n500\n1000\n2000\n5000\nYou can withdraw no more than 9900 at a time\nEnter your amount:\nYou entered the amount less than the minimum, please try again\nDeposit money (Press D)\nWithdraw money (Press W)\nCheck balance (Press B)\nQuit (Press Q)\nATM dispenses the following bills:\n100\n500\n1000\n2000\n5000\nYou can withdraw no more than 9900 at a time\nEnter your amount:\nYou entered the amount that exceeds the maximum withdraw at a time, please try again\nDeposit money (Press D)\nWithdraw money (Press W)\nCheck balance (Press B)\nQuit (Press Q)\nATM dispenses the following bills:\n100\n500\n1000\n2000\n5000\nYou can withdraw no more than 9900 at a time\nEnter your amount:\nYou entered the wrong bill, please try again\nDeposit money (Press D)\nWithdraw money (Press W)\nCheck balance (Press B)\nQuit (Press Q)\nATM dispenses the following bills:\n100\n500\n1000\n2000\n5000\nYou can withdraw no more than 9900 at a time\nEnter your amount:\nYou entered the amount that exceeds your current balance, please try again\nDeposit money (Press D)\nWithdraw money (Press W)\nCheck balance (Press B)\nQuit (Press Q)\nATM dispenses the following bills:\n100\n500\n1000\n2000\n5000\nYou can withdraw no more than 9900 at a time\nEnter your amount:\nYour balance: 4000\nDeposit money (Press D)\nWithdraw money (Press W)\nCheck balance (Press B)\nQuit (Press Q)\n").to_stdout
  end
end
